#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/voxis}"
BRANCH="${BRANCH:-NeuronMap}"
PM2_APP_NAME="${PM2_APP_NAME:-voxis-backend}"
APP_NAME="${APP_NAME:-voxis}"
STASH_NAME="Pre-deploy auto-stash $(date +%Y-%m-%d_%H-%M-%S)"
STASH_CREATED=0

echo "=== Safe Voxis Deploy Started ==="
echo "App dir: ${APP_DIR}"
echo "Branch: ${BRANCH}"

cd "${APP_DIR}"

echo "→ Fetching latest changes..."
git fetch origin

# package-lock.json is always regenerated by npm install and should never block pulls.
# Restore it to the committed version before stashing/pulling.
git checkout -- package-lock.json 2>/dev/null || true

echo "→ Stashing any remaining local changes..."
if ! git stash push -u -m "${STASH_NAME}" 2>&1 | grep -q "No local changes to save"; then
  STASH_CREATED=1
fi

echo "→ Checking out ${BRANCH}..."
git checkout "${BRANCH}" 2>/dev/null || git checkout -b "${BRANCH}" "origin/${BRANCH}"

echo "→ Pulling latest code..."
git pull origin "${BRANCH}" --ff-only || git pull origin "${BRANCH}" --rebase

echo "→ Installing dependencies..."
npm install

echo "→ Ensuring prosody tools are installed..."
if ! command -v yt-dlp >/dev/null 2>&1 || ! command -v ffmpeg >/dev/null 2>&1 || ! command -v ffprobe >/dev/null 2>&1; then
	sudo apt-get update -y
	sudo apt-get install -y yt-dlp ffmpeg
fi

echo "→ Building frontend..."
npm run build

echo "→ Restarting backend..."
export VOXIS_GIT_SHA="$(git -C "${APP_DIR}" rev-parse --short HEAD)"
export VOXIS_BRANCH="${BRANCH}"
export PM2_APP_NAME

# Source backend/.env into the current shell so PM2 picks up every variable,
# including TTS_ENGINE. PM2 does NOT read .env files itself.
if [[ -f "${APP_DIR}/backend/.env" ]]; then
	echo "  Sourcing backend/.env into shell environment"
	set -o allexport
	# shellcheck source=/dev/null
	source "${APP_DIR}/backend/.env"
	set +o allexport
fi

if [[ -f "${APP_DIR}/ecosystem.config.cjs" ]]; then
	pm2 startOrReload "${APP_DIR}/ecosystem.config.cjs" --only "${PM2_APP_NAME}" --update-env
else
	pm2 restart "${PM2_APP_NAME}" --update-env
fi
pm2 save >/dev/null 2>&1 || true

echo "→ Configuring Nginx..."
NGINX_SITE="/etc/nginx/sites-available/$APP_NAME"
BACKEND_PORT="${BACKEND_PORT:-3101}"
SERVER_NAME="${SERVER_NAME:-$(hostname -f)}"

# Required routes that must appear in the Nginx config.
NGINX_NEEDS_UPDATE=0
if [[ ! -f "$NGINX_SITE" ]]; then
  NGINX_NEEDS_UPDATE=1
elif ! grep -q 'personality-preference' "$NGINX_SITE" \
  || ! grep -q 'loop' "$NGINX_SITE" \
  || ! grep -q 'sfx' "$NGINX_SITE" \
  || ! grep -q "127.0.0.1:${BACKEND_PORT}" "$NGINX_SITE"; then
  NGINX_NEEDS_UPDATE=1
fi

if [[ "$NGINX_NEEDS_UPDATE" -eq 1 ]]; then
  echo "  Writing Nginx config for ${APP_NAME} → port ${BACKEND_PORT}..."
  sudo tee "$NGINX_SITE" >/dev/null <<NGINXEOF
server {
    listen 80;
    listen [::]:80;
    server_name ${SERVER_NAME};

    root ${APP_DIR}/frontend/dist;
    index index.html;
    client_max_body_size 30m;

    location ~ ^/(api|health|chat|settings|me|users|personality|personality-preference|personalities|research-profile|memory|tts|voice-presets|loop|loops|sfx|preferences|prosody|voice-sample|user-memory|performance)(/|\$) {
        proxy_pass http://127.0.0.1:${BACKEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        add_header X-Accel-Buffering no;
    }

    location / {
        try_files \$uri /index.html;
    }
}
NGINXEOF
  sudo ln -sfn "$NGINX_SITE" "/etc/nginx/sites-enabled/$APP_NAME"
  if [[ -L /etc/nginx/sites-enabled/default ]]; then
    sudo rm -f /etc/nginx/sites-enabled/default
  fi
  echo "  Nginx config written."
else
  echo "  Nginx config OK (no update needed)."
fi

sudo nginx -t && sudo systemctl reload nginx

if [[ "${STASH_CREATED}" -eq 1 ]]; then
	echo "→ Cleaning up deploy stash..."
	STASH_REF=$(git stash list | grep -F "${STASH_NAME}" | head -n1 | cut -d: -f1)
	if [[ -n "${STASH_REF}" ]]; then
		git stash drop "${STASH_REF}"
	fi
fi

echo "=== Safe Voxis Deploy Completed Successfully ==="