#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/voxis}"
BRANCH="${BRANCH:-NeuronMap}"
PM2_APP_NAME="${PM2_APP_NAME:-voxis-backend}"
APP_NAME="${APP_NAME:-voxis}"
STASH_NAME="Pre-deploy auto-stash $(date +%Y-%m-%d_%H-%M-%S)"
STASH_CREATED=0

echo "=== Safe Voxis Deploy Started ==="
echo "App dir: ${APP_DIR}"
echo "Branch: ${BRANCH}"

cd "${APP_DIR}"

echo "→ Fetching latest changes..."
git fetch origin

# package-lock.json is always regenerated by npm install and should never block pulls.
# Restore it to the committed version before stashing/pulling.
git checkout -- package-lock.json 2>/dev/null || true

echo "→ Stashing any remaining local changes..."
if ! git stash push -u -m "${STASH_NAME}" 2>&1 | grep -q "No local changes to save"; then
  STASH_CREATED=1
fi

echo "→ Checking out ${BRANCH}..."
git checkout "${BRANCH}" 2>/dev/null || git checkout -b "${BRANCH}" "origin/${BRANCH}"

echo "→ Pulling latest code..."
git pull origin "${BRANCH}" --ff-only || git pull origin "${BRANCH}" --rebase

echo "→ Installing dependencies..."
npm install

echo "→ Ensuring prosody tools are installed..."
if ! command -v yt-dlp >/dev/null 2>&1 || ! command -v ffmpeg >/dev/null 2>&1 || ! command -v ffprobe >/dev/null 2>&1; then
	sudo apt-get update -y
	sudo apt-get install -y yt-dlp ffmpeg
fi

echo "→ Building frontend..."
npm run build

echo "→ Restarting backend..."
export VOXIS_GIT_SHA="$(git -C "${APP_DIR}" rev-parse --short HEAD)"
export VOXIS_BRANCH="${BRANCH}"
export PM2_APP_NAME

# Source backend/.env into the current shell so PM2 picks up every variable,
# including TTS_ENGINE. PM2 does NOT read .env files itself.
if [[ -f "${APP_DIR}/backend/.env" ]]; then
	echo "  Sourcing backend/.env into shell environment"
	set -o allexport
	# shellcheck source=/dev/null
	source "${APP_DIR}/backend/.env"
	set +o allexport
fi

if [[ -f "${APP_DIR}/ecosystem.config.cjs" ]]; then
	pm2 startOrReload "${APP_DIR}/ecosystem.config.cjs" --only "${PM2_APP_NAME}" --update-env
else
	pm2 restart "${PM2_APP_NAME}" --update-env
fi
pm2 save >/dev/null 2>&1 || true

echo "→ Reloading nginx..."
sudo systemctl reload nginx

NGINX_SITE="/etc/nginx/sites-available/$APP_NAME"
if [[ -f "$NGINX_SITE" ]]; then
	if ! grep -q 'personality-preference' "$NGINX_SITE" || ! grep -q '(api|' "$NGINX_SITE"; then
		echo "WARNING: nginx site ${NGINX_SITE} is missing newer API proxy routes."
		echo "Production may miss preferences, loops, SFX, and other newer frontend-backed features."
		echo "Reapply the nginx config from deploy/setup-ubuntu.sh, then run: sudo nginx -t && sudo systemctl reload nginx"
	fi
fi

if [[ "${STASH_CREATED}" -eq 1 ]]; then
	echo "→ Cleaning up deploy stash..."
	STASH_REF=$(git stash list | grep -F "${STASH_NAME}" | head -n1 | cut -d: -f1)
	if [[ -n "${STASH_REF}" ]]; then
		git stash drop "${STASH_REF}"
	fi
fi

echo "=== Safe Voxis Deploy Completed Successfully ==="