export {
  MERLIN_PRODUCT_CLAIM,
  MERLIN_PRODUCT_TAGLINE,
  MERLIN_VOICE_SYSTEM_BLOCK,
  VOICE_FLUFF_PATTERNS,
  VOICE_FORTUNE_PATTERNS,
  VOICE_TECH_LEAD_PATTERNS,
  applyMerlinVoicePass,
  failsMerlinVoiceTest,
  formatThreeLayerPlain,
  lintMerlinVoice,
  softRewriteMerlinVoice,
  type MerlinThreeLayerCopy,
  type VoiceLintResult,
} from '@/lib/voice/merlin-voice';
